from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Literal

from pydantic import BaseModel, ConfigDict, Field

from libs.common.yaml_config import load_yaml_mapping


class StrategyConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    type: Literal["turnaround_sheet", "img2img_views"] = Field(...)


class ModelConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    type: Literal["sdxl_diffusers"] = Field(...)
    path: str = Field(...)
    device: str = Field(..., description='"cuda" or "cpu"')


class PromptConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    character_description: str = Field(...)
    style: str = Field(...)
    negative_prompt: str = Field(...)


class ControlNetConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    enabled: bool = Field(...)
    path: str = Field(..., description="ControlNet model path for SDXL (e.g., canny).")
    conditioning_scale: float = Field(..., description="0..1, lower = weaker control.")
    low_threshold: int = Field(..., description="Canny low threshold.")
    high_threshold: int = Field(..., description="Canny high threshold.")


class OutputConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    out_dir: str = Field(...)
    sheet_png: str = Field(...)
    front_png: str = Field(...)
    left_png: str = Field(...)
    back_png: str = Field(...)
    right_png: str = Field(...)
    view_width: int = Field(..., description="Resize each cropped view to this width.")
    view_height: int = Field(..., description="Resize each cropped view to this height.")


class GenerationConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    width: int = Field(...)
    height: int = Field(...)
    steps: int = Field(...)
    guidance: float = Field(...)
    seed: int = Field(..., description="Used for turnaround_sheet. For img2img_views, see base_seed/view seeds.")


class Img2ImgConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    base_png: str = Field(..., description="Base identity image generated by txt2img.")
    base_seed: int = Field(...)
    strength_default: float = Field(..., description="0..1, higher changes more.")


class ViewGenConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    id: Literal["front", "left", "back", "right"] = Field(...)
    seed: int = Field(...)
    strength: float = Field(..., description="0..1, overrides strength_default.")
    prompt_suffix: str = Field(..., description='Extra prompt text, e.g. "back view".')
    pose_image: str = Field(..., description="Pose reference image for ControlNet (canny).")


class LayoutConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    rows: int = Field(...)
    cols: int = Field(...)
    order: Dict[str, int] = Field(..., description="Mapping: front/left/back/right -> cell index (row-major).")


class AppConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    strategy: StrategyConfig = Field(...)
    model: ModelConfig = Field(...)
    prompt: PromptConfig = Field(...)
    controlnet: ControlNetConfig = Field(...)
    output: OutputConfig = Field(...)
    generation: GenerationConfig = Field(...)
    layout: LayoutConfig = Field(...)
    img2img: Img2ImgConfig = Field(...)
    views: List[ViewGenConfig] = Field(...)

    @classmethod
    def from_yaml(cls, path: Path) -> "AppConfig":
        return cls.model_validate(load_yaml_mapping(path))

